#https://github.com/TheElectronWill/night-config
nightconfig_version=3.8.1

#https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu_version=11.0.3
#https://modrinth.com/mod/raised/versions?platform=fabric
raised_version=Fabric-1.21.1-5.0.0

#https://modrinth.com/mod/appleskin/versions?l=fabric
appleskin_version=3.0.6+mc1.21
#https://linkie.shedaniel.dev
clothconfig_version=15.0.140

#https://modrinth.com/mod/forge-config-api-port/versions?l=fabric
forgeconfig_version=v21.1.4-1.21.1-Fabric
#https://modrinth.com/mod/overflowing-bars/versions?l=fabric
overflowingbars_version=v21.1.1-1.21.1-Fabric
#https://modrinth.com/mod/puzzles-lib/versions?l=fabric
puzzleslib_version=v21.1.36-1.21.1-Fabric
