#https://github.com/TheElectronWill/night-config
nightconfig_version=3.8.1

#https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu_version=18.0.0-alpha.8
#https://modrinth.com/mod/raised/versions?platform=fabric
raised_version=Fabric-26.1.1-5.1.2

#https://modrinth.com/mod/appleskin/versions?l=fabric
appleskin_version=3.0.9+mc26.1
#https://linkie.shedaniel.dev
clothconfig_version=26.1.154

#https://modrinth.com/mod/forge-config-api-port/versions?l=fabric
forgeconfig_version=26.1.4
#https://modrinth.com/mod/overflowing-bars/versions?l=fabric
overflowingbars_version=26.1.0
#https://modrinth.com/mod/puzzles-lib/versions?l=fabric
puzzleslib_version=26.1.2

#https://modrinth.com/mod/farmers-delight-refabricated/versions
farmersdelight_version=26.1-3.5.5
fabricasm_version=v2.3
