#https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu_version=17.0.0
#https://modrinth.com/mod/raised/versions?platform=fabric
raised_version=Fabric-1.21.11-5.1.2

#https://modrinth.com/mod/appleskin/versions?l=fabric
appleskin_version=3.0.8+mc1.21.11
#https://linkie.shedaniel.dev
clothconfig_version=21.11.153

#https://modrinth.com/mod/forge-config-api-port/versions?l=fabric
forgeconfig_version=21.11.1
#https://modrinth.com/mod/overflowing-bars/versions?l=fabric
overflowingbars_version=21.11.0
#https://modrinth.com/mod/puzzles-lib/versions?l=fabric
puzzleslib_version=21.11.13

#https://modrinth.com/mod/farmers-delight-refabricated/versions
farmersdelight_version=1.21.11-3.4.9
fabricasm_version=v2.3
