#https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu_version=20.0.0-beta.4
#https://modrinth.com/mod/raised/versions?platform=fabric
raised_version=Fabric-26.1.1-5.1.2

#https://modrinth.com/mod/appleskin/versions?l=fabric
appleskin_version=3.0.10+mc26.2
#https://linkie.shedaniel.dev
#clothconfig_version=17.0.144

#https://modrinth.com/mod/forge-config-api-port/versions?l=fabric
forgeconfig_version=26.2.1
#https://modrinth.com/mod/overflowing-bars/versions?l=fabric
overflowingbars_version=26.2.0
#https://modrinth.com/mod/puzzles-lib/versions?l=fabric
puzzleslib_version=26.2.0

#https://modrinth.com/mod/farmers-delight-refabricated/versions
farmersdelight_version=26.2-3.6.6
