plugins {
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'dev.architectury.loom' version '1.13-SNAPSHOT' apply false
    id 'com.gradleup.shadow' version '8.3.6' apply false
    id "com.modrinth.minotaur" version "2.+" apply false
    id 'net.darkhax.curseforgegradle' version '1.1.+' apply false
}

architectury {
    minecraft = project.minecraft_version
}

// all subprojects
configure(subprojects.findAll { it.name == "common" || it.name == "fabric" || it.name == "neoforge" }) {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'

    architectury {
        compileOnly()
        injectInjectables = false
    }

    loom {
        silentMojangMappingsLicense()
        mixin.useLegacyMixinAp = false
    }

    repositories {
        maven { url = "https://maven.parchmentmc.org" }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings loom.layered() {

            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.parchment_version}@zip" as String)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = "UTF-8"
        it.options.release = 21
    }
}

// all non-common subprojects
configure(subprojects.findAll { it.name == "fabric" || it.name == "neoforge" }) {
    apply plugin: 'maven-publish'

    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }
    }

    tasks.withType(GenerateModuleMetadata).configureEach {
        enabled = false
    }

    publishing {
        publications {
            maven(MavenPublication) {
                var isApi = project.path.startsWith(":api")
                var isExtensions = project.path.startsWith(":extensions")

                groupId = project.group
                artifactId = "colorfulhearts-${project.name}${isApi ? "-api" : isExtensions ? "-extensions" : ""}"
                from components.java
                // From https://github.com/Fuzss/modresources/blob/d40b8125cadb6ab1b56d90c03eb0c09a666d949a/gradle/v2/main.gradle#L235-L260
                pom {
                    name = "Colorful Hearts${isApi ? " API" : isExtensions ? " Extensions" : ""}"
                    description = "A client side mod that replaces multiple vanilla heart rows with a single row using colored hearts"
                    url = "https://github.com/Terrails/colorful-hearts"
                    scm {
                        url = "https://github.com/Terrails/colorful-hearts"
                        connection = "scm:git:git://github.com/Terrails/colorful-hearts.git"
                        developerConnection = "scm:git:git@github.com:Terrails/colorful-hearts.git"
                    }
                    issueManagement {
                        system = "github"
                        url = "https://github.com/Terrails/colorful-hearts/issues"
                    }
                    licenses {
                        license {
                            name = "MIT"
                            url = "https://spdx.org/licenses/MIT.html"
                        }
                    }
                    developers {
                        developer {
                            id = "terrails"
                            name = "Terrails"
                        }
                    }
                }
            }
        }

        if (System.getenv("MODMAVEN_PATH")) {
            def mavenPath = System.getenv("MODMAVEN_PATH")
            if (file(mavenPath).exists()) {
                repositories {
                    maven {
                        name = "ModMaven"
                        url "file://" + System.getenv("MODMAVEN_PATH")
                    }
                }
            }
        }
    }
}
