plugins {
    id 'architectury-plugin' version '3.5-SNAPSHOT'
    id 'dev.architectury.loom' version '1.17-SNAPSHOT' apply false
    id 'com.gradleup.shadow' version '8.3.6' apply false
    id "com.modrinth.minotaur" version "2.+" apply false
    id 'net.darkhax.curseforgegradle' version '1.1.+' apply false
}

architectury {
    minecraft = project.minecraft_version
}

// all subprojects
configure(subprojects.findAll { it.name == "common" || it.name == "fabric" || it.name == "neoforge" }) {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'

    architectury {
        compileOnly()
        injectInjectables = false
    }

    loom {
        silentMojangMappingsLicense()
        mixin.useLegacyMixinAp = false
    }

    repositories {
        maven { url = "https://maven.parchmentmc.org" }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings loom.layered() {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.parchment_version}@zip" as String)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = "UTF-8"
        it.options.release = 21
    }
}

// all non-common subprojects
configure(subprojects.findAll { it.name == "fabric" || it.name == "neoforge" }) {
    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }
    }
}
