org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

## Project
minecraft_version=1.21.1
parchment_version=2024.11.17

mod_version=10.5.9

curseforge_id=854213
modrinth_id=wQfMUdZT

## Fabric
#https://fabricmc.net/develop/
fabric_loader_version=0.16.14
fabric_api_version=0.116.4+1.21.1

## NeoForge
#https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.195
