org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

## Project
minecraft_version=26.1.2
parchment_version=2024.11.17

mod_version=10.5.9

curseforge_id=854213
modrinth_id=wQfMUdZT

## Fabric
#https://fabricmc.net/develop/
fabric_loader_version=0.19.2
fabric_api_version=0.147.0+26.1.2

## NeoForge
#https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.30-beta
