org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

## Project
minecraft_version=26.1.2
min_minecraft_version=26.1.2

## Fabric
#https://fabricmc.net/develop/
fabric_loader_version=0.19.3
fabric_api_version=0.150.0+26.1.2
#https://github.com/TheElectronWill/night-config
nightconfig_version=3.8.4

## NeoForge
#https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.71
