loom.platform=neoforge

#https://modrinth.com/mod/farmers-delight/versions?l=neoforge
#farmersdelight_version=1.21.1-1.2.8
#https://modrinth.com/mod/the-undergarden/versions?l=neoforge
#undergarden_version=0.9.3
#https://modrinth.com/mod/raised/versions?platform=neoforge
raised_version=NeoForge-26.1.1-5.1.2

#https://modrinth.com/mod/appleskin/versions?l=neoforge
appleskin_version=3.0.9+mc26.1
#https://linkie.shedaniel.dev
clothconfig_version=26.1.154

#https://modrinth.com/mod/forge-config-api-port/versions?l=neoforge
forgeconfig_version=26.1.4
#https://modrinth.com/mod/overflowing-bars/versions?l=neoforge
overflowingbars_version=26.1.0
#https://modrinth.com/mod/puzzles-lib/versions?l=neoforge
puzzleslib_version=26.1.9
