loom.platform=neoforge

#https://modrinth.com/mod/farmers-delight/versions?l=neoforge
farmersdelight_version=1.21.1-1.2.8
#https://modrinth.com/mod/the-undergarden/versions?l=neoforge
undergarden_version=0.9.3
#https://modrinth.com/mod/raised/versions?platform=neoforge
raised_version=NeoForge-1.21.4-5.1.2

#https://modrinth.com/mod/appleskin/versions?l=neoforge
appleskin_version=3.0.8+mc1.21.3
#https://linkie.shedaniel.dev
clothconfig_version=17.0.144

#https://modrinth.com/mod/forge-config-api-port/versions?l=neoforge
forgeconfig_version=v21.4.3-1.21.4-NeoForge
#https://modrinth.com/mod/overflowing-bars/versions?l=neoforge
overflowingbars_version=v21.4.0-1.21.4-NeoForge
#https://modrinth.com/mod/puzzles-lib/versions?l=neoforge
puzzleslib_version=v21.4.14-1.21.4-NeoForge
