plugins {
    id 'com.gradleup.shadow'
    id 'com.modrinth.minotaur'
    id 'net.darkhax.curseforgegradle'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    runs {
        server.ideConfigGenerated(false)
        // set window size to 720p
        client.programArgs("--width", "1280", "--height", "720")
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven { url "https://maven.neoforged.net/releases/" }
}

dependencies {
    neoForge "net.neoforged:neoforge:${neoforge_version}"

    common(project(path: ':api:common', configuration: 'namedElements')) { transitive false }
    common(project(path: ':api:neoforge', configuration: 'namedElements')) { transitive false }
    common(project(path: ':base:common', configuration: 'namedElements')) { transitive false }
    shadowBundle(project(path: ':api:common', configuration: 'transformProductionNeoForge'))
    shadowBundle(project(path: ':api:neoforge', configuration: 'namedElements')) { transitive false }
    shadowBundle(project(path: ':base:common', configuration: 'transformProductionNeoForge'))
    include(project(path: ':extensions:neoforge', configuration: 'shadowArtifact')) { transitive false }
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

remapJar {
    input.set shadowJar.archiveFile
    atAccessWideners.add(loom.accessWidenerPath.get().asFile.name)
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

tasks.build.mustRunAfter(tasks.clean)
tasks.register('publishProduction') {
    dependsOn([tasks.clean, tasks.build])
    finalizedBy([tasks.modrinth, tasks.publishCurseForge])
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "${project.modrinth_id}"
    versionNumber = "${project.version}"
    versionName = "[NeoForge] ${project.minecraft_version}-v${project.version}"
    uploadFile = tasks.remapJar.getArchiveFile().get()
    gameVersions = [project.minecraft_version]
    loaders = ["neoforge"]
    changelog = rootProject.file("CHANGELOG.md").text
}

import net.darkhax.curseforgegradle.TaskPublishCurseForge

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    apiToken = System.getenv("CURSEFORGE_TOKEN")
    disableVersionDetection()

    def mainFile = upload(project.curseforge_id, tasks.remapJar.getArchiveFile().get())
    mainFile.displayName = "[NeoForge] ${project.minecraft_version}-v${project.version}"
    mainFile.releaseType = "release"
    mainFile.changelog = rootProject.file("CHANGELOG.md").text
    mainFile.changelogType = "markdown"
    mainFile.addGameVersion("Client", project.minecraft_version)
    mainFile.addModLoader("neoforge")
}
