loom.platform=neoforge

#https://modrinth.com/mod/farmers-delight/versions?l=neoforge
farmersdelight_version=1.21.1-1.2.8
#https://modrinth.com/mod/the-undergarden/versions?l=neoforge
undergarden_version=0.9.3
#https://modrinth.com/mod/raised/versions?platform=neoforge
raised_version=NeoForge-1.21.1-5.0.0

#https://modrinth.com/mod/appleskin/versions?l=neoforge
appleskin_version=3.0.7+mc1.21
#https://linkie.shedaniel.dev
clothconfig_version=15.0.140

#https://modrinth.com/mod/forge-config-api-port/versions?l=neoforge
forgeconfig_version=v21.1.4-1.21.1-NeoForge
#https://modrinth.com/mod/overflowing-bars/versions?l=neoforge
overflowingbars_version=v21.1.1-1.21.1-NeoForge
#https://modrinth.com/mod/puzzles-lib/versions?l=neoforge
puzzleslib_version=v21.1.36-1.21.1-NeoForge
