allprojects {
    group = "terrails.colorfulhearts.api" // required to prevent circular dependency
    version = project.mod_version
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'

    base {
        archivesBaseName = "colorfulhearts-api-${project.name}-${project.minecraft_version}"
    }

    java {
        withSourcesJar()
    }

    loom {
        accessWidenerPath = project(":base:common").file("src/main/resources/colorfulhearts.accesswidener")

        if (project.path != ':api:common') {
            mods {
                main {
                    sourceSet project.sourceSets.main
                    sourceSet project(':api:common').sourceSets.main
                }
            }
        }
    }
}
