name: Publish

on:
  workflow_dispatch:

jobs:
  publish-production:
    runs-on: ubuntu-latest
    environment: deploy
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Read mod version
        id: version
        run: |
          VERSION=$(grep '^mod_version=' base/gradle.properties | cut -d'=' -f2)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Check whether release already exists
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ steps.version.outputs.version }}
        run: |
          if gh release view "$RELEASE_NAME" >/dev/null 2>&1; then
            echo "Release $RELEASE_NAME already exists."
            exit 1
          fi
          echo "Release $RELEASE_NAME does not exist."

      - name: Check whether changelog entry exists
        id: changelog
        env:
          RELEASE_NAME: ${{ steps.version.outputs.version }}
        run: |
          NOTES=$(sed -n "/^## \[$RELEASE_NAME\]/,/^## /p" ./CHANGELOG.md | sed "\$d")

          if [ -z "$NOTES" ]; then
            echo "No changelog entry found for version $RELEASE_NAME in CHANGELOG.md"
            exit 1
          fi

          # Store multiline output safely
          {
            echo "notes<<EOF"
            echo "$NOTES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          
          echo "Changelog entry for $RELEASE_NAME found."

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew build

      #      - name: Run publishProduction
      #        env:
      #          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      #          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      #        run: ./gradlew :base:fabric:publishProduction :base:neoforge:publishProduction

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ steps.version.outputs.version }}
          CHANGELOG_NOTES: ${{ steps.changelog.outputs.notes }}
        run: |
          gh release create "$RELEASE_NAME" \
            --title "Colorful Hearts v$RELEASE_NAME" \
            --notes "$CHANGELOG_NOTES" \
            base/fabric/build/libs/*[0-9].jar \
            base/neoforge/build/libs/*[0-9].jar
