modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Terrails/colorful-hearts"
license = "MIT"

[[mods]]
modId = "colorfulhearts-extensions"
version = "${version}"

displayName = "Colorful Hearts Extensions"
authors = "Terrails"
description = ''' An extension mod for colorful-hearts adding compatibility with other mods. '''

logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION" # ignore everything since it's a client only mod

[[mixins]]
config = "colorfulhearts-extensions.mixins.json"

[[dependencies.colorfulhearts-extensions]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.colorfulhearts-extensions]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.colorfulhearts-extensions]]
modId = "colorfulhearts"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

