modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Terrails/colorful-hearts/issues"
license = "MIT"

[[mods]]
modId = "colorfulhearts_extensions"
version = "${mod_version}"

displayName = "Colorful Hearts Extensions"
authors = "Terrails"
description = ''' An extension mod for colorful-hearts adding compatibility with other mods. '''

logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION" # ignore everything since it's a client only mod

[[mixins]]
config = "colorfulhearts_extensions.mixins.json"

[[dependencies.colorfulhearts_extensions]]
modId = "minecraft"
type = "required"
versionRange = "[${min_minecraft_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.colorfulhearts_extensions]]
modId = "neoforge"
type = "required"
versionRange = "[${min_neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.colorfulhearts_extensions]]
modId = "colorfulhearts"
type = "required"
versionRange = "[${min_colorfulhearts_version},)"
ordering = "NONE"
side = "CLIENT"
